# Generated by Django 4.2.13 on 2024-07-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_author_status_author_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True)),
                ('category_description', models.TextField()),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
    ]
