# Generated by Django 4.2.13 on 2024-07-06 18:36

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('cover_img', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('short_description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('rating_average', models.FloatField(default=0.0)),
                ('likes', models.IntegerField(default=0)),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Genre', to='book.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='book.author')),
            ],
            options={
                'ordering': ['created_on', 'title'],
            },
        ),
    ]
